spring:
  application:
    name: java-customer-onboarding-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/customers_onboarding}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:postgres}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Customer Onboarding API
    version: v1
server:
  port: ${SERVER_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health,info

zip-code:
  wiremock:
    base-url: ${ZIP_CODE_WIREMOCK_BASE_URL:http://localhost:8081}
  viacep:
    base-url: ${ZIP_CODE_VIACEP_BASE_URL:https://viacep.com.br/ws}

document-storage:
  base-path: ${DOCUMENT_STORAGE_BASE_PATH:uploads}
